/**
 * FlowAccount Open API
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthenResponse from '../model/AuthenResponse';

/**
* Authentication service.
* @module api/AuthenticationApi
* @version 2-oas3
*/
export default class AuthenticationApi {

    /**
    * Constructs a new AuthenticationApi. 
    * @alias module:api/AuthenticationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the tokenPost operation.
     * @callback module:api/AuthenticationApi~tokenPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuthenResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate Access Token
     * @param {String} contentType 
     * @param {Object} opts Optional parameters
     * @param {String} opts.grantType 
     * @param {String} opts.scope 
     * @param {String} opts.clientId 
     * @param {String} opts.clientSecret 
     * @param {String} opts.guid 
     * @param {module:api/AuthenticationApi~tokenPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AuthenResponse}
     */
    tokenPost(contentType, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'contentType' is set
      if (contentType === undefined || contentType === null) {
        throw new Error("Missing the required parameter 'contentType' when calling tokenPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'Content-Type': contentType
      };
      let formParams = {
        'grant_type': opts['grantType'],
        'scope': opts['scope'],
        'client_id': opts['clientId'],
        'client_secret': opts['clientSecret'],
        'guid': opts['guid']
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = AuthenResponse;
      return this.apiClient.callApi(
        '/token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
