# coding: utf-8

"""
    FlowAccount Open API

    # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64  # noqa: E501

    The version of the OpenAPI document: 2-oas3
    Contact: developer_support@flowaccount.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ReferencedToMe(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'reference_id': 'int',
        'reference_document_type': 'int',
        'reference_document_serial': 'str',
        'document_id': 'int',
        'document_serial': 'int',
        'type': 'int'
    }

    attribute_map = {
        'reference_id': 'referenceId',
        'reference_document_type': 'referenceDocumentType',
        'reference_document_serial': 'referenceDocumentSerial',
        'document_id': 'documentId',
        'document_serial': 'documentSerial',
        'type': 'type'
    }

    def __init__(self, reference_id=None, reference_document_type=None, reference_document_serial=None, document_id=None, document_serial=None, type=1, local_vars_configuration=None):  # noqa: E501
        """ReferencedToMe - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._reference_id = None
        self._reference_document_type = None
        self._reference_document_serial = None
        self._document_id = None
        self._document_serial = None
        self._type = None
        self.discriminator = None

        if reference_id is not None:
            self.reference_id = reference_id
        if reference_document_type is not None:
            self.reference_document_type = reference_document_type
        if reference_document_serial is not None:
            self.reference_document_serial = reference_document_serial
        if document_id is not None:
            self.document_id = document_id
        if document_serial is not None:
            self.document_serial = document_serial
        if type is not None:
            self.type = type

    @property
    def reference_id(self):
        """Gets the reference_id of this ReferencedToMe.  # noqa: E501

        ID เอกสารฉบับนี้  # noqa: E501

        :return: The reference_id of this ReferencedToMe.  # noqa: E501
        :rtype: int
        """
        return self._reference_id

    @reference_id.setter
    def reference_id(self, reference_id):
        """Sets the reference_id of this ReferencedToMe.

        ID เอกสารฉบับนี้  # noqa: E501

        :param reference_id: The reference_id of this ReferencedToMe.  # noqa: E501
        :type: int
        """

        self._reference_id = reference_id

    @property
    def reference_document_type(self):
        """Gets the reference_document_type of this ReferencedToMe.  # noqa: E501

        ประเภทของเอกสารฉบับนี้  # noqa: E501

        :return: The reference_document_type of this ReferencedToMe.  # noqa: E501
        :rtype: int
        """
        return self._reference_document_type

    @reference_document_type.setter
    def reference_document_type(self, reference_document_type):
        """Sets the reference_document_type of this ReferencedToMe.

        ประเภทของเอกสารฉบับนี้  # noqa: E501

        :param reference_document_type: The reference_document_type of this ReferencedToMe.  # noqa: E501
        :type: int
        """

        self._reference_document_type = reference_document_type

    @property
    def reference_document_serial(self):
        """Gets the reference_document_serial of this ReferencedToMe.  # noqa: E501

        เลขที่เอกสารฉบับนี้  # noqa: E501

        :return: The reference_document_serial of this ReferencedToMe.  # noqa: E501
        :rtype: str
        """
        return self._reference_document_serial

    @reference_document_serial.setter
    def reference_document_serial(self, reference_document_serial):
        """Sets the reference_document_serial of this ReferencedToMe.

        เลขที่เอกสารฉบับนี้  # noqa: E501

        :param reference_document_serial: The reference_document_serial of this ReferencedToMe.  # noqa: E501
        :type: str
        """

        self._reference_document_serial = reference_document_serial

    @property
    def document_id(self):
        """Gets the document_id of this ReferencedToMe.  # noqa: E501

        ID เอกสารปลายทางที่อ้างอิง ถึง เอกสารฉบับนี้  # noqa: E501

        :return: The document_id of this ReferencedToMe.  # noqa: E501
        :rtype: int
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this ReferencedToMe.

        ID เอกสารปลายทางที่อ้างอิง ถึง เอกสารฉบับนี้  # noqa: E501

        :param document_id: The document_id of this ReferencedToMe.  # noqa: E501
        :type: int
        """

        self._document_id = document_id

    @property
    def document_serial(self):
        """Gets the document_serial of this ReferencedToMe.  # noqa: E501

        เลขที่เอกสารปลายทางที่อ้างอิง ถึง เอกสารฉบับนี้  # noqa: E501

        :return: The document_serial of this ReferencedToMe.  # noqa: E501
        :rtype: int
        """
        return self._document_serial

    @document_serial.setter
    def document_serial(self, document_serial):
        """Sets the document_serial of this ReferencedToMe.

        เลขที่เอกสารปลายทางที่อ้างอิง ถึง เอกสารฉบับนี้  # noqa: E501

        :param document_serial: The document_serial of this ReferencedToMe.  # noqa: E501
        :type: int
        """

        self._document_serial = document_serial

    @property
    def type(self):
        """Gets the type of this ReferencedToMe.  # noqa: E501


        :return: The type of this ReferencedToMe.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ReferencedToMe.


        :param type: The type of this ReferencedToMe.  # noqa: E501
        :type: int
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReferencedToMe):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReferencedToMe):
            return True

        return self.to_dict() != other.to_dict()
