name: OpenAPIClient
targets:
  OpenAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [OpenAPIClient]
    info:
      path: ./Info.plist
      version: 2-oas3
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
