/**
 * FlowAccount Open API
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BusinessCategory {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("systemCode")
  private Integer systemCode = null;
  @SerializedName("categoryId")
  private Integer categoryId = null;
  @SerializedName("categoryNameLocal")
  private String categoryNameLocal = null;
  @SerializedName("categoryNameForeign")
  private String categoryNameForeign = null;
  @SerializedName("debitId")
  private Integer debitId = null;
  @SerializedName("debitCategory")
  private Integer debitCategory = null;
  @SerializedName("debitCode")
  private String debitCode = null;
  @SerializedName("debitNameLocal")
  private String debitNameLocal = null;
  @SerializedName("debitNameForeign")
  private String debitNameForeign = null;
  @SerializedName("creditId")
  private Integer creditId = null;
  @SerializedName("creditCategory")
  private Integer creditCategory = null;
  @SerializedName("creditCode")
  private String creditCode = null;
  @SerializedName("creditNameLocal")
  private String creditNameLocal = null;
  @SerializedName("creditNameForeign")
  private String creditNameForeign = null;
  @SerializedName("keywords")
  private String keywords = null;

  /**
   * id ของหมวดหมู่ค่าใช้จ่าย
   **/
  @ApiModelProperty(value = "id ของหมวดหมู่ค่าใช้จ่าย")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * เลขที่ system code หมวดหมู่ค่าใช้จ่าย (เลือกใช้ หมวดหมู่ค่าใช้จ่ายสำหรับธุรกิจ)
   **/
  @ApiModelProperty(value = "เลขที่ system code หมวดหมู่ค่าใช้จ่าย (เลือกใช้ หมวดหมู่ค่าใช้จ่ายสำหรับธุรกิจ)")
  public Integer getSystemCode() {
    return systemCode;
  }
  public void setSystemCode(Integer systemCode) {
    this.systemCode = systemCode;
  }

  /**
   * เลขที่ id หมวดหมู่ค่าใช้จ่าย (เลือกใช้ หมวดหมู่ค่าใช้จ่ายสำหรับธุรกิจ)
   **/
  @ApiModelProperty(value = "เลขที่ id หมวดหมู่ค่าใช้จ่าย (เลือกใช้ หมวดหมู่ค่าใช้จ่ายสำหรับธุรกิจ)")
  public Integer getCategoryId() {
    return categoryId;
  }
  public void setCategoryId(Integer categoryId) {
    this.categoryId = categoryId;
  }

  /**
   * ชื่อหมวดหมู่ค่าใช้จ่าย
   **/
  @ApiModelProperty(value = "ชื่อหมวดหมู่ค่าใช้จ่าย")
  public String getCategoryNameLocal() {
    return categoryNameLocal;
  }
  public void setCategoryNameLocal(String categoryNameLocal) {
    this.categoryNameLocal = categoryNameLocal;
  }

  /**
   * ชื่อหมวดหมู่ค่าใช้จ่าย (ภาษาอังกฤษ)
   **/
  @ApiModelProperty(value = "ชื่อหมวดหมู่ค่าใช้จ่าย (ภาษาอังกฤษ)")
  public String getCategoryNameForeign() {
    return categoryNameForeign;
  }
  public void setCategoryNameForeign(String categoryNameForeign) {
    this.categoryNameForeign = categoryNameForeign;
  }

  /**
   * เลข id หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต
   **/
  @ApiModelProperty(value = "เลข id หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต")
  public Integer getDebitId() {
    return debitId;
  }
  public void setDebitId(Integer debitId) {
    this.debitId = debitId;
  }

  /**
   * เลขหมวดหมู่ ฝั่งเดบิต ของ หมวดหมู่ค่าใช้จ่าย
   **/
  @ApiModelProperty(value = "เลขหมวดหมู่ ฝั่งเดบิต ของ หมวดหมู่ค่าใช้จ่าย")
  public Integer getDebitCategory() {
    return debitCategory;
  }
  public void setDebitCategory(Integer debitCategory) {
    this.debitCategory = debitCategory;
  }

  /**
   * เลขที่หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต
   **/
  @ApiModelProperty(value = "เลขที่หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต")
  public String getDebitCode() {
    return debitCode;
  }
  public void setDebitCode(String debitCode) {
    this.debitCode = debitCode;
  }

  /**
   * ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต
   **/
  @ApiModelProperty(value = "ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต")
  public String getDebitNameLocal() {
    return debitNameLocal;
  }
  public void setDebitNameLocal(String debitNameLocal) {
    this.debitNameLocal = debitNameLocal;
  }

  /**
   * ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต (ภาษาอังกฤษ)
   **/
  @ApiModelProperty(value = "ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเดบิต (ภาษาอังกฤษ)")
  public String getDebitNameForeign() {
    return debitNameForeign;
  }
  public void setDebitNameForeign(String debitNameForeign) {
    this.debitNameForeign = debitNameForeign;
  }

  /**
   * เลข id หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิิต
   **/
  @ApiModelProperty(value = "เลข id หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิิต")
  public Integer getCreditId() {
    return creditId;
  }
  public void setCreditId(Integer creditId) {
    this.creditId = creditId;
  }

  /**
   * เลขหมวดหมู่ ฝั่งเครดิต ของ หมวดหมู่ค่าใช้จ่าย
   **/
  @ApiModelProperty(value = "เลขหมวดหมู่ ฝั่งเครดิต ของ หมวดหมู่ค่าใช้จ่าย")
  public Integer getCreditCategory() {
    return creditCategory;
  }
  public void setCreditCategory(Integer creditCategory) {
    this.creditCategory = creditCategory;
  }

  /**
   * เลขที่หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิต
   **/
  @ApiModelProperty(value = "เลขที่หมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิต")
  public String getCreditCode() {
    return creditCode;
  }
  public void setCreditCode(String creditCode) {
    this.creditCode = creditCode;
  }

  /**
   * ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิต 
   **/
  @ApiModelProperty(value = "ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิต ")
  public String getCreditNameLocal() {
    return creditNameLocal;
  }
  public void setCreditNameLocal(String creditNameLocal) {
    this.creditNameLocal = creditNameLocal;
  }

  /**
   * ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิต (ภาษาอังกฤษ)
   **/
  @ApiModelProperty(value = "ชื่อหมวดหมู่ค่าใช้จ่ายทางบัญชี ฝั่งเครดิต (ภาษาอังกฤษ)")
  public String getCreditNameForeign() {
    return creditNameForeign;
  }
  public void setCreditNameForeign(String creditNameForeign) {
    this.creditNameForeign = creditNameForeign;
  }

  /**
   * keyword
   **/
  @ApiModelProperty(value = "keyword")
  public String getKeywords() {
    return keywords;
  }
  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessCategory businessCategory = (BusinessCategory) o;
    return (this.id == null ? businessCategory.id == null : this.id.equals(businessCategory.id)) &&
        (this.systemCode == null ? businessCategory.systemCode == null : this.systemCode.equals(businessCategory.systemCode)) &&
        (this.categoryId == null ? businessCategory.categoryId == null : this.categoryId.equals(businessCategory.categoryId)) &&
        (this.categoryNameLocal == null ? businessCategory.categoryNameLocal == null : this.categoryNameLocal.equals(businessCategory.categoryNameLocal)) &&
        (this.categoryNameForeign == null ? businessCategory.categoryNameForeign == null : this.categoryNameForeign.equals(businessCategory.categoryNameForeign)) &&
        (this.debitId == null ? businessCategory.debitId == null : this.debitId.equals(businessCategory.debitId)) &&
        (this.debitCategory == null ? businessCategory.debitCategory == null : this.debitCategory.equals(businessCategory.debitCategory)) &&
        (this.debitCode == null ? businessCategory.debitCode == null : this.debitCode.equals(businessCategory.debitCode)) &&
        (this.debitNameLocal == null ? businessCategory.debitNameLocal == null : this.debitNameLocal.equals(businessCategory.debitNameLocal)) &&
        (this.debitNameForeign == null ? businessCategory.debitNameForeign == null : this.debitNameForeign.equals(businessCategory.debitNameForeign)) &&
        (this.creditId == null ? businessCategory.creditId == null : this.creditId.equals(businessCategory.creditId)) &&
        (this.creditCategory == null ? businessCategory.creditCategory == null : this.creditCategory.equals(businessCategory.creditCategory)) &&
        (this.creditCode == null ? businessCategory.creditCode == null : this.creditCode.equals(businessCategory.creditCode)) &&
        (this.creditNameLocal == null ? businessCategory.creditNameLocal == null : this.creditNameLocal.equals(businessCategory.creditNameLocal)) &&
        (this.creditNameForeign == null ? businessCategory.creditNameForeign == null : this.creditNameForeign.equals(businessCategory.creditNameForeign)) &&
        (this.keywords == null ? businessCategory.keywords == null : this.keywords.equals(businessCategory.keywords));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.systemCode == null ? 0: this.systemCode.hashCode());
    result = 31 * result + (this.categoryId == null ? 0: this.categoryId.hashCode());
    result = 31 * result + (this.categoryNameLocal == null ? 0: this.categoryNameLocal.hashCode());
    result = 31 * result + (this.categoryNameForeign == null ? 0: this.categoryNameForeign.hashCode());
    result = 31 * result + (this.debitId == null ? 0: this.debitId.hashCode());
    result = 31 * result + (this.debitCategory == null ? 0: this.debitCategory.hashCode());
    result = 31 * result + (this.debitCode == null ? 0: this.debitCode.hashCode());
    result = 31 * result + (this.debitNameLocal == null ? 0: this.debitNameLocal.hashCode());
    result = 31 * result + (this.debitNameForeign == null ? 0: this.debitNameForeign.hashCode());
    result = 31 * result + (this.creditId == null ? 0: this.creditId.hashCode());
    result = 31 * result + (this.creditCategory == null ? 0: this.creditCategory.hashCode());
    result = 31 * result + (this.creditCode == null ? 0: this.creditCode.hashCode());
    result = 31 * result + (this.creditNameLocal == null ? 0: this.creditNameLocal.hashCode());
    result = 31 * result + (this.creditNameForeign == null ? 0: this.creditNameForeign.hashCode());
    result = 31 * result + (this.keywords == null ? 0: this.keywords.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessCategory {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  systemCode: ").append(systemCode).append("\n");
    sb.append("  categoryId: ").append(categoryId).append("\n");
    sb.append("  categoryNameLocal: ").append(categoryNameLocal).append("\n");
    sb.append("  categoryNameForeign: ").append(categoryNameForeign).append("\n");
    sb.append("  debitId: ").append(debitId).append("\n");
    sb.append("  debitCategory: ").append(debitCategory).append("\n");
    sb.append("  debitCode: ").append(debitCode).append("\n");
    sb.append("  debitNameLocal: ").append(debitNameLocal).append("\n");
    sb.append("  debitNameForeign: ").append(debitNameForeign).append("\n");
    sb.append("  creditId: ").append(creditId).append("\n");
    sb.append("  creditCategory: ").append(creditCategory).append("\n");
    sb.append("  creditCode: ").append(creditCode).append("\n");
    sb.append("  creditNameLocal: ").append(creditNameLocal).append("\n");
    sb.append("  creditNameForeign: ").append(creditNameForeign).append("\n");
    sb.append("  keywords: ").append(keywords).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
