/**
 * FlowAccount Open API
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.SendEmail;
import org.openapitools.client.model.SendEmailCoppiesAllOf;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SendEmailCoppies extends SendEmail {
  
  @SerializedName("documentId")
  private Long documentId = null;
  @SerializedName("fromemail")
  private String fromemail = null;
  @SerializedName("toemail")
  private String toemail = null;
  @SerializedName("cCMyself")
  private Boolean cCMyself = true;
  @SerializedName("ccEmail")
  private String ccEmail = null;
  @SerializedName("bccEmail")
  private String bccEmail = null;
  @SerializedName("subject")
  private String subject = null;
  @SerializedName("message")
  private String message = null;
  @SerializedName("doCopy")
  private Boolean doCopy = true;

  /**
   * documentId หรือ recordId ของเอกสารที่ต้องการส่งอีเมล
   **/
  @ApiModelProperty(required = true, value = "documentId หรือ recordId ของเอกสารที่ต้องการส่งอีเมล")
  public Long getDocumentId() {
    return documentId;
  }
  public void setDocumentId(Long documentId) {
    this.documentId = documentId;
  }

  /**
   * ใส่อีเมลผู้ส่ง <br> <ex>Example: myemail@email.com</ex>
   **/
  @ApiModelProperty(required = true, value = "ใส่อีเมลผู้ส่ง <br> <ex>Example: myemail@email.com</ex>")
  public String getFromemail() {
    return fromemail;
  }
  public void setFromemail(String fromemail) {
    this.fromemail = fromemail;
  }

  /**
   * ใส่อีเมลผู้รับ <br> <ex>Example: contact@email.com</ex>
   **/
  @ApiModelProperty(required = true, value = "ใส่อีเมลผู้รับ <br> <ex>Example: contact@email.com</ex>")
  public String getToemail() {
    return toemail;
  }
  public void setToemail(String toemail) {
    this.toemail = toemail;
  }

  /**
   * ส่งสำเนาหาตนเอง
   **/
  @ApiModelProperty(value = "ส่งสำเนาหาตนเอง")
  public Boolean getCCMyself() {
    return cCMyself;
  }
  public void setCCMyself(Boolean cCMyself) {
    this.cCMyself = cCMyself;
  }

  /**
   * สำเนา (CC) <br> <ex>Example: cc@email.com</ex>
   **/
  @ApiModelProperty(value = "สำเนา (CC) <br> <ex>Example: cc@email.com</ex>")
  public String getCcEmail() {
    return ccEmail;
  }
  public void setCcEmail(String ccEmail) {
    this.ccEmail = ccEmail;
  }

  /**
   * สำเนาลับ (BCC) <br> <ex>Example: bcc@email.com</ex>
   **/
  @ApiModelProperty(value = "สำเนาลับ (BCC) <br> <ex>Example: bcc@email.com</ex>")
  public String getBccEmail() {
    return bccEmail;
  }
  public void setBccEmail(String bccEmail) {
    this.bccEmail = bccEmail;
  }

  /**
   * หัวข้อ / ชื่อเรื่อง 
   **/
  @ApiModelProperty(required = true, value = "หัวข้อ / ชื่อเรื่อง ")
  public String getSubject() {
    return subject;
  }
  public void setSubject(String subject) {
    this.subject = subject;
  }

  /**
   * ข้อความ เนื้อหาของ email
   **/
  @ApiModelProperty(value = "ข้อความ เนื้อหาของ email")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }

  /**
   * ส่งต้นฉบับ พร้อม สำเนา
   **/
  @ApiModelProperty(value = "ส่งต้นฉบับ พร้อม สำเนา")
  public Boolean getDoCopy() {
    return doCopy;
  }
  public void setDoCopy(Boolean doCopy) {
    this.doCopy = doCopy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendEmailCoppies sendEmailCoppies = (SendEmailCoppies) o;
    return (this.documentId == null ? sendEmailCoppies.documentId == null : this.documentId.equals(sendEmailCoppies.documentId)) &&
        (this.fromemail == null ? sendEmailCoppies.fromemail == null : this.fromemail.equals(sendEmailCoppies.fromemail)) &&
        (this.toemail == null ? sendEmailCoppies.toemail == null : this.toemail.equals(sendEmailCoppies.toemail)) &&
        (this.cCMyself == null ? sendEmailCoppies.cCMyself == null : this.cCMyself.equals(sendEmailCoppies.cCMyself)) &&
        (this.ccEmail == null ? sendEmailCoppies.ccEmail == null : this.ccEmail.equals(sendEmailCoppies.ccEmail)) &&
        (this.bccEmail == null ? sendEmailCoppies.bccEmail == null : this.bccEmail.equals(sendEmailCoppies.bccEmail)) &&
        (this.subject == null ? sendEmailCoppies.subject == null : this.subject.equals(sendEmailCoppies.subject)) &&
        (this.message == null ? sendEmailCoppies.message == null : this.message.equals(sendEmailCoppies.message)) &&
        (this.doCopy == null ? sendEmailCoppies.doCopy == null : this.doCopy.equals(sendEmailCoppies.doCopy));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.documentId == null ? 0: this.documentId.hashCode());
    result = 31 * result + (this.fromemail == null ? 0: this.fromemail.hashCode());
    result = 31 * result + (this.toemail == null ? 0: this.toemail.hashCode());
    result = 31 * result + (this.cCMyself == null ? 0: this.cCMyself.hashCode());
    result = 31 * result + (this.ccEmail == null ? 0: this.ccEmail.hashCode());
    result = 31 * result + (this.bccEmail == null ? 0: this.bccEmail.hashCode());
    result = 31 * result + (this.subject == null ? 0: this.subject.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    result = 31 * result + (this.doCopy == null ? 0: this.doCopy.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendEmailCoppies {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  documentId: ").append(documentId).append("\n");
    sb.append("  fromemail: ").append(fromemail).append("\n");
    sb.append("  toemail: ").append(toemail).append("\n");
    sb.append("  cCMyself: ").append(cCMyself).append("\n");
    sb.append("  ccEmail: ").append(ccEmail).append("\n");
    sb.append("  bccEmail: ").append(bccEmail).append("\n");
    sb.append("  subject: ").append(subject).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("  doCopy: ").append(doCopy).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
