//
// BankAccountResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BankAccountResponseData: Codable { 


    /** เลข id บัญชีธนาคาร */
    public var bankAccountId: Int64?
    /** เลขบัญชี &lt;br&gt; &lt;ex&gt;Example: 0048620000 &lt;/ex&gt; */
    public var bankAccountNumber: String?
    /** ชื่อบัญชี &lt;br&gt; &lt;ex&gt;Example: บัญชีใช้รับเงิน&lt;/ex&gt; */
    public var bankAccountName: String?
    /** ประเภทบัญชีธนาคาร &lt;br&gt; 1 &#x3D; บัญชีออมทรัพย์  &lt;br&gt; 3 &#x3D; บัญชีกระรายวัน &lt;br&gt; 7  &#x3D; บัญชีฝากประจำ */
    public var bankAccountType: Int64?
    /** ชื่อสาขาธนาคาร */
    public var bankBranch: String?
    /** เลข id ธนาคาร */
    public var bankId: Int64?
    /** ชื่อธนาคาร */
    public var bankName: String?

    public init(bankAccountId: Int64?, bankAccountNumber: String?, bankAccountName: String?, bankAccountType: Int64?, bankBranch: String?, bankId: Int64?, bankName: String?) {
        self.bankAccountId = bankAccountId
        self.bankAccountNumber = bankAccountNumber
        self.bankAccountName = bankAccountName
        self.bankAccountType = bankAccountType
        self.bankBranch = bankBranch
        self.bankId = bankId
        self.bankName = bankName
    }

}
