//
// InlineObject9.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject9: Codable { 


    public var grantType: String?
    public var scope: String?
    public var clientId: String?
    public var clientSecret: String?
    public var guid: String?

    public init(grantType: String?, scope: String?, clientId: String?, clientSecret: String?, guid: String?) {
        self.grantType = grantType
        self.scope = scope
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.guid = guid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case grantType = "grant_type"
        case scope
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case guid
    }

}
