//
// SendEmailResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** data success */
public struct SendEmailResponseData: Codable { 


    /** Status */
    public var ok: Bool?
    /** Email sent successfully */
    public var message: String?
    /** Change Status Complete */
    public var successMsg: String?

    public init(ok: Bool?, message: String?, successMsg: String?) {
        self.ok = ok
        self.message = message
        self.successMsg = successMsg
    }

}
