# coding: utf-8

"""
    FlowAccount Open API

    FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น   # Introduction **Servers Production**    site: https://www.flowaccount.com    api url: https://openapi.flowaccount.com/v1    **Beta test**   site: http://sandbox-new.flowaccount.com/    api url: https://openapi.flowaccount.com/test  # noqa: E501

    The version of the OpenAPI document: 2-oas3
    Contact: developer@flowaccount.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.expense_inline_document_response import ExpenseInlineDocumentResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestExpenseInlineDocumentResponse(unittest.TestCase):
    """ExpenseInlineDocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpenseInlineDocumentResponse(self):
        """Test ExpenseInlineDocumentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.expense_inline_document_response.ExpenseInlineDocumentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
