/*
 * FlowAccount Open API
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BankAccount
 */
public class BankAccountTest {
    private final BankAccount model = new BankAccount();

    /**
     * Model tests for BankAccount
     */
    @Test
    public void testBankAccount() {
        // TODO: test BankAccount
    }

    /**
     * Test the property 'bankAccountNumber'
     */
    @Test
    public void bankAccountNumberTest() {
        // TODO: test bankAccountNumber
    }

    /**
     * Test the property 'bankAccountName'
     */
    @Test
    public void bankAccountNameTest() {
        // TODO: test bankAccountName
    }

    /**
     * Test the property 'bankAccountType'
     */
    @Test
    public void bankAccountTypeTest() {
        // TODO: test bankAccountType
    }

    /**
     * Test the property 'bankBranch'
     */
    @Test
    public void bankBranchTest() {
        // TODO: test bankBranch
    }

    /**
     * Test the property 'bankId'
     */
    @Test
    public void bankIdTest() {
        // TODO: test bankId
    }

}
