/* 
 * FlowAccount Open API
 *
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น   # Introduction **Servers Production**    site: https://www.flowaccount.com    api url: https://openapi.flowaccount.com/v1    **Beta test**   site: http://sandbox-new.flowaccount.com/    api url: https://openapi.flowaccount.com/test    **PostMan Collection**   site: https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CompanyInfoResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompanyInfoResponseAllOfTests
    {
        // TODO uncomment below to declare an instance variable for CompanyInfoResponseAllOf
        //private CompanyInfoResponseAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompanyInfoResponseAllOf
            //instance = new CompanyInfoResponseAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompanyInfoResponseAllOf
        /// </summary>
        [Test]
        public void CompanyInfoResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CompanyInfoResponseAllOf
            //Assert.IsInstanceOf(typeof(CompanyInfoResponseAllOf), instance);
        }


        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }

    }

}
