/* 
 * FlowAccount Open API
 *
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentResponseTests
    {
        // TODO uncomment below to declare an instance variable for DocumentResponse
        //private DocumentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentResponse
            //instance = new DocumentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentResponse
        /// </summary>
        [Test]
        public void DocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DocumentResponse
            //Assert.IsInstanceOf(typeof(DocumentResponse), instance);
        }

        /// <summary>
        /// Test deserialize a InlineDocumentResponse from type DocumentResponse
        /// </summary>
        [Test]
        public void InlineDocumentResponseDeserializeFromDocumentResponseTest()
        {
            // TODO uncomment below to test deserialize a InlineDocumentResponse from type DocumentResponse
            //Assert.IsInstanceOf(typeof(DocumentResponse), JsonConvert.DeserializeObject<DocumentResponse>(new InlineDocumentResponse().ToJson()));
        }
        /// <summary>
        /// Test deserialize a SimpleDocumentResponse from type DocumentResponse
        /// </summary>
        [Test]
        public void SimpleDocumentResponseDeserializeFromDocumentResponseTest()
        {
            // TODO uncomment below to test deserialize a SimpleDocumentResponse from type DocumentResponse
            //Assert.IsInstanceOf(typeof(DocumentResponse), JsonConvert.DeserializeObject<DocumentResponse>(new SimpleDocumentResponse().ToJson()));
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'DocumentStructureType'
        /// </summary>
        [Test]
        public void DocumentStructureTypeTest()
        {
            // TODO unit test for the property 'DocumentStructureType'
        }

    }

}
