/* 
 * FlowAccount Open API
 *
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flowaccount.OpenAPITools.Api;
using Flowaccount.OpenAPITools.Model;
using Flowaccount.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flowaccount.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SimpleDocumentResponseAllOfDataCompany
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimpleDocumentResponseAllOfDataCompanyTests
    {
        // TODO uncomment below to declare an instance variable for SimpleDocumentResponseAllOfDataCompany
        //private SimpleDocumentResponseAllOfDataCompany instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SimpleDocumentResponseAllOfDataCompany
            //instance = new SimpleDocumentResponseAllOfDataCompany();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SimpleDocumentResponseAllOfDataCompany
        /// </summary>
        [Test]
        public void SimpleDocumentResponseAllOfDataCompanyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SimpleDocumentResponseAllOfDataCompany
            //Assert.IsInstanceOf(typeof(SimpleDocumentResponseAllOfDataCompany), instance);
        }


        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyNameEn'
        /// </summary>
        [Test]
        public void CompanyNameEnTest()
        {
            // TODO unit test for the property 'CompanyNameEn'
        }
        /// <summary>
        /// Test the property 'CompanyAddress'
        /// </summary>
        [Test]
        public void CompanyAddressTest()
        {
            // TODO unit test for the property 'CompanyAddress'
        }
        /// <summary>
        /// Test the property 'CompanyAddressEn'
        /// </summary>
        [Test]
        public void CompanyAddressEnTest()
        {
            // TODO unit test for the property 'CompanyAddressEn'
        }
        /// <summary>
        /// Test the property 'CompanyTaxId'
        /// </summary>
        [Test]
        public void CompanyTaxIdTest()
        {
            // TODO unit test for the property 'CompanyTaxId'
        }
        /// <summary>
        /// Test the property 'CompanyBranch'
        /// </summary>
        [Test]
        public void CompanyBranchTest()
        {
            // TODO unit test for the property 'CompanyBranch'
        }
        /// <summary>
        /// Test the property 'CompanyBranchEn'
        /// </summary>
        [Test]
        public void CompanyBranchEnTest()
        {
            // TODO unit test for the property 'CompanyBranchEn'
        }
        /// <summary>
        /// Test the property 'CompanyPhone'
        /// </summary>
        [Test]
        public void CompanyPhoneTest()
        {
            // TODO unit test for the property 'CompanyPhone'
        }
        /// <summary>
        /// Test the property 'CompanyMobile'
        /// </summary>
        [Test]
        public void CompanyMobileTest()
        {
            // TODO unit test for the property 'CompanyMobile'
        }
        /// <summary>
        /// Test the property 'CompanyFax'
        /// </summary>
        [Test]
        public void CompanyFaxTest()
        {
            // TODO unit test for the property 'CompanyFax'
        }
        /// <summary>
        /// Test the property 'CompanyWebsite'
        /// </summary>
        [Test]
        public void CompanyWebsiteTest()
        {
            // TODO unit test for the property 'CompanyWebsite'
        }

    }

}
