/**
 * FlowAccount Open API
 * # Introduction  **Servers Production**    <site>Site:</site> https://www.flowaccount.com    <site>Api url:</site> https://openapi.flowaccount.com/v1    **Beta test**   <site>Site:</site> http://sandbox-new.flowaccount.com/    <site>Api url:</site> https://openapi.flowaccount.com/test    **PostMan Collection**   <site>Link:</site> https://www.getpostman.com/collections/01e7c68d7093e2092a64
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer_support@flowaccount.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlowAccountOpenApi);
  }
}(this, function(expect, FlowAccountOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FlowAccountOpenApi.QuotationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuotationsApi', function() {
    describe('quotationsEmailDocumentPost', function() {
      it('should call quotationsEmailDocumentPost successfully', function(done) {
        //uncomment below and update the code to test quotationsEmailDocumentPost
        //instance.quotationsEmailDocumentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsGet', function() {
      it('should call quotationsGet successfully', function(done) {
        //uncomment below and update the code to test quotationsGet
        //instance.quotationsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsIdAttachmentPost', function() {
      it('should call quotationsIdAttachmentPost successfully', function(done) {
        //uncomment below and update the code to test quotationsIdAttachmentPost
        //instance.quotationsIdAttachmentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsIdDelete', function() {
      it('should call quotationsIdDelete successfully', function(done) {
        //uncomment below and update the code to test quotationsIdDelete
        //instance.quotationsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsIdGet', function() {
      it('should call quotationsIdGet successfully', function(done) {
        //uncomment below and update the code to test quotationsIdGet
        //instance.quotationsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsIdPut', function() {
      it('should call quotationsIdPut successfully', function(done) {
        //uncomment below and update the code to test quotationsIdPut
        //instance.quotationsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsIdStatusStatusIdPost', function() {
      it('should call quotationsIdStatusStatusIdPost successfully', function(done) {
        //uncomment below and update the code to test quotationsIdStatusStatusIdPost
        //instance.quotationsIdStatusStatusIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsInlinePost', function() {
      it('should call quotationsInlinePost successfully', function(done) {
        //uncomment below and update the code to test quotationsInlinePost
        //instance.quotationsInlinePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsPost', function() {
      it('should call quotationsPost successfully', function(done) {
        //uncomment below and update the code to test quotationsPost
        //instance.quotationsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('quotationsSharedocumentPost', function() {
      it('should call quotationsSharedocumentPost successfully', function(done) {
        //uncomment below and update the code to test quotationsSharedocumentPost
        //instance.quotationsSharedocumentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
