<?php
/**
 * ReceivingInventoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowAccount Open API
 *
 * FlowAccount.com โปรแกรมบัญชีออนไลน์ใช้งานง่าย สำหรับธุรกิจที่พึ่งเริ่มต้น   # Introduction **Servers Production**    site: https://www.flowaccount.com    api url: https://openapi.flowaccount.com/v1    **Beta test**   site: http://sandbox-new.flowaccount.com/    api url: https://openapi.flowaccount.com/test
 *
 * The version of the OpenAPI document: 2-oas3
 * Contact: developer@flowaccount.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReceivingInventoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReceivingInventoryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for purchasesEmailDocumentPost
     *
     * Send email receiving inventory document..
     *
     */
    public function testPurchasesEmailDocumentPost()
    {
    }

    /**
     * Test case for purchasesGet
     *
     * Get list all receiving inventory documents..
     *
     */
    public function testPurchasesGet()
    {
    }

    /**
     * Test case for purchasesIdAttachmentPost
     *
     * Add Attachment to receiving inventory document..
     *
     */
    public function testPurchasesIdAttachmentPost()
    {
    }

    /**
     * Test case for purchasesIdDelete
     *
     * Get receiving inventory document..
     *
     */
    public function testPurchasesIdDelete()
    {
    }

    /**
     * Test case for purchasesIdGet
     *
     * Get receiving inventory document..
     *
     */
    public function testPurchasesIdGet()
    {
    }

    /**
     * Test case for purchasesIdStatusKeyStatusIdPost
     *
     * Change status of receiving inventory document..
     *
     */
    public function testPurchasesIdStatusKeyStatusIdPost()
    {
    }

    /**
     * Test case for purchasesInlinePost
     *
     * Create receiving inventory document with discount and tax inline..
     *
     */
    public function testPurchasesInlinePost()
    {
    }

    /**
     * Test case for purchasesPost
     *
     * Create receiving inventory document..
     *
     */
    public function testPurchasesPost()
    {
    }

    /**
     * Test case for purchasesSharedocumentPost
     *
     * Share link receiving inventory document..
     *
     */
    public function testPurchasesSharedocumentPost()
    {
    }
}
